# Generated by Django 3.0 on 2021-04-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='store',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
