# Generated by Django 3.0 on 2021-04-19 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registers', '0004_auto_20210419_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
